### ISSUE TITLE
How to check for callback responses?

### ISSUE THREAD

**Issue by bettblake08** [safaricom/mpesa-php-sdk#13]
Hi,
Thanks for this sdk.
I would like to know how to check for callback responses to determine if m route needs to be debugged.
The curl requests are processed successfully but i am not receiving any callback responses.

**Comment by mossey** [comment]
Hello @bettblake08 great question... To check whether any callbacks are getting to you, can look at your server access logs. This way you will be able to see all the request hitting your web-service.

**Comment by bettblake08** [comment]
Ok thanks

**Comment by nellycheboi12** [comment]
@mossey I am interacting with the Mpesa Api test endpoint i.e https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate for C2B request. I am still not getting any data at my callback server. Do you send responses even tests or is it just for production/live purposes. I fully debugged my callback server and I am able to get pings/request just not from Mpesa.

**Comment by mossey** [comment]
Hello @nellycheboi12, first of all sorry for the late response. Responses are sent even for applications on sandbox. Just make sure that the callback urls are publicly accessible from the internet

**Comment by kamula** [comment]
@mossey  how can i get the responses from the applications on the sandbox
