### ISSUE TITLE
STKPushQuery() has a bug

### ISSUE THREAD

**Issue by mkihuha** [safaricom/mpesa-php-sdk#20]
Kindly update the public static function STKPushQuery() to exclude the $live or $environment parameter as this creates confusion when using this function. The user ends with an error similar to the one below:

"Type error: Too few arguments to function Safaricom\Mpesa\Mpesa::STKPushQuery(), 4 passed in /home/vagrant/code/myProject/app/Http/Controllers/PaymentsController.php on line 73 and exactly 5 expected"

After amending the aforementioned function, my code is now working as expected

**Comment by mossey** [comment]
Hello @mkihuha the issue has been addressed in a PR that I just accepted. Thanks for raising it
