### ISSUE TITLE
How to register new urls

### ISSUE THREAD

**Issue by abijahm** [safaricom/mpesa-php-sdk#32]
is there a way to register new urls
registering new urls responds with
```
{ ConversationID: '',
  OriginatorCoversationID: '',
  ResponseDescription: 'Validation and Confirmation URLs are already registered' }

```

**Comment by peter-mayeku** [comment]
@abijahm check out this tutorial it will be of great help

https://www.youtube.com/watch?v=FoD14ucjCx4&index=6&list=PLcKuwRUZRXZL36Lb3e5eryz8K4mmrqgqs

**Comment by abijahm** [comment]
Solved by sending safaricom a email requesting deletion of old urls
