### ISSUE TITLE
AccountBalance API returns "The initiator information is invalid."

### ISSUE THREAD

**Issue by qlint** [safaricom/mpesa-php-sdk#41]
I've followed the documentation for the `AccountBalance` but keep ending up with the same message, that the Initiator information is invalid. I'm assuming this could be one of two possibilites, either the `$Initiator` value is wrong or the `$SecurityCredential`. 

**This is how I'm computing the $securityCredential**
```php
    $plainTextPwd = 'somePassword';
    $pubKeyFile =  __DIR__ . "/cert/cert.cer";
    $publicKey = '';
    if(\is_file($pubKeyFile)){
        $publicKey = file_get_contents($pubKeyFile);
        openssl_public_encrypt($plainTextPwd, $encrypted, $publicKey, OPENSSL_PKCS1_PADDING);
        $securityCredential = base64_encode($encrypted);
        echo $securityCredential; // This is my $SecurityCredential value
    }else{
        throw new \Exception("Please provide a valid public key file");
    }
```
Which gives me a `$securityCredential` which is 344 characters long. 

**As for the $Initiator**
This is what the documentation says at https://developer.safaricom.co.ke/account-balance/apis/post/query
> **Initiator**
> This is the credential/username used to authenticate the transaction request 

My confusion is - what is **credential/username** given that there is an initiator username and there is an initiator credential (assuming credential means password)?

I've tried using either but still get the same message though - **"Initiator information is invalid."**. What could be happening?

**Comment by kelvinthiongo** [comment]
Why does Safaricom ignore all these issues, very sad? I am facing the same problem too but no help.

**Comment by kievo23** [comment]
I am stuck too. For two weeks.
Safaricom's monopoly is hurting the market.

**Comment by mossey** [comment]
Hi All,
There exists an issue in the documentation and I intend to make a fix to it. 

To clarify, the check account balance method takes these parameters: `$CommandID, $Initiator, $SecurityCredential, $PartyA, $IdentifierType, $Remarks, $QueueTimeOutURL, $ResultURL`

The issue of initiator information is invalid is caused by you using a wrong combination of `$Initiator` and  `$SecurityCredential`. 
Looking at my test credentials below,

<img width="1046" alt="Screenshot 2021-01-04 at 14 03 51" src="https://user-images.githubusercontent.com/5586471/103745480-9d148a80-5010-11eb-8fa7-92da0e63577b.png">


Looking at the test credentials shared above, the  `$Initiator` field should be populated by the value of `Initiator Name (Shortcode 1)` which in this case is `Safaricomapi`. In production, It is the name of the API initiator that you create on the org portal. 

The `$SecurityCredential` field is populated by encrypting the value of  `Security Credential (Shortcode 1)` using the production certificate when in production or sandbox certificate when in sandbox. The security credential value does not change unless you change the initiator password in the org portal in prod. You may generate the security credential by doing an encryption of its value below the credentials as shown on the screenshot below. 
<img width="834" alt="Screenshot 2021-01-06 at 11 35 42" src="https://user-images.githubusercontent.com/5586471/103747264-6db34d00-5013-11eb-95ec-127bf343c3c2.png">

**Comment by Whizboy-Arnold** [comment]
> Hi All, There exists an issue in the documentation and I intend to make a fix to it.
> 
> To clarify, the check account balance method takes these parameters: `$CommandID, $Initiator, $SecurityCredential, $PartyA, $IdentifierType, $Remarks, $QueueTimeOutURL, $ResultURL`
> 
> The issue of initiator information is invalid is caused by you using a wrong combination of `$Initiator` and `$SecurityCredential`. Looking at my test credentials below,
> 
> <img alt="Screenshot 2021-01-04 at 14 03 51" width="1046" src="https://user-images.githubusercontent.com/5586471/103745480-9d148a80-5010-11eb-8fa7-92da0e63577b.png">
> 
> Looking at the test credentials shared above, the `$Initiator` field should be populated by the value of `Initiator Name (Shortcode 1)` which in this case is `Safaricomapi`. In production, It is the name of the API initiator that you create on the org portal.
> 
> The `$SecurityCredential` field is populated by encrypting the value of `Security Credential (Shortcode 1)` using the production certificate when in production or sandbox certificate when in sandbox. The security credential value does not change unless you change the initiator password in the org portal in prod. You may generate the security credential by doing an encryption of its value below the credentials as shown on the screenshot below. <img alt="Screenshot 2021-01-06 at 11 35 42" width="834" src="https://user-images.githubusercontent.com/5586471/103747264-6db34d00-5013-11eb-95ec-127bf343c3c2.png">

where do i get these test credentials in the new api.  there is no such a page and the ones on the simulator don;t seem towork

**Comment by Whizboy-Arnold** [comment]
where do i get these test credentials in the new api. there is no such a page and the ones on the simulator don;t seem towork

**Comment by asifsami73** [comment]
While trying to b2c, I'm getting this error, The initiator's information is invalid, I can't find any solution to this problem.

**Comment by tmhevencent** [comment]
Has anyone succeeded in this securityCredential thing, i have tried using certificate and openssl but still getting the error. Safaricom daraja has no clear formats of generating securityCredential.

**Comment by qlint** [comment]
> Has anyone succeeded in this securityCredential thing, i have tried using certificate and openssl but still getting the error. Safaricom daraja has no clear formats of generating securityCredential.

Try this:

```
$pass = "YOUR-PASSWORD-IN-https://org.ke.m-pesa.com";
$publicKey = file_get_contents('./your-path-to/ProductionCertificate.cer');
openssl_public_encrypt($pass, $encrypted, $publicKey, OPENSSL_PKCS1_PADDING);
$securityCredentials = base64_encode($encrypted);
```

**Comment by MarkxOBrian** [comment]
For those like me who are here looking for Test credentials for Daraja API V2 Sandbox, you can send an email to **APIfeedback@safaricom.co.ke** or **APIsupport@safaricom.co.ke** and they will send you updated credentials. I realised they get updated after a while.

**Comment by barasapeter** [comment]
I bumped into that issue and here is how I fixed it:

First you need to create an API user and assign the Business BuyGoods API initiator role. Once created the user can proceed initiate B2B API requests. 

Kindly find below a step by step process for creating API operator/initiator and setting their password:
Step 1 : Create a Business Manager
Login on MPESA portal, https://org.ke.m-pesa.com/  as the Business administrator
Select operators
Then click the add option
It will take you to a new page where you will enter the username of the operator,
Select access channel as Web
Then select web profile default rule profile
Then assign role...Business Manager and Set Restricted ORG API PASSWORD.
Enter the KYC information of the operator then submit

Step 2: Create an API operator 
Log in as the Business administrator
Select operators
Then click the add option
It will take you to a new page where you will enter the username of the API initiator ,
Select access channel as API
Then select web profile default rule profile
Then assign role...look for the ORG B2C API initiator, Balance Query ORG API, Transaction Status query ORG API roles
Enter the KYC information of the operator then submit

Step 3: Setting the API Users password. 
Here is how to set the password for the API user
Login as User with the Set Restrict Password Role i.e. The Business Manager
Click on My Functions, Then Operator Management.
Enter the API username to search
after it populates the API user, At the end click on operations
Then click on set password.
