### ISSUE TITLE
mpesa payment b2c

### ISSUE THREAD

**Issue by himanshupatel95** [safaricom/mpesa-php-sdk#7]
Fatal error: Call to undefined function Safaricom\Mpesa\env() in
env() error.

**Comment by mossey** [comment]
Hi @himanshupatel95. What were you trying to achieve when you encountered this? Have you defined your environmental variables? If not you need to define them.

**Comment by KipchirchirIan** [comment]
Encountered the same issue as well.

![mpesa-err-1](https://user-images.githubusercontent.com/3757280/45120040-b4ec5300-b165-11e8-8323-3452da74677b.png)

The code:
```php
$stkPushSimulation = $mpesa->STKPushSimulation(
   "174379",
   "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919",
   "CustomerPayBillOnline",
   "10",
   "254720123123",
   "174379",
   "254720123123",
   "https://example.com/callback.php",
   "Abc 123",
   "Testing Mpesa API",
   "MPesa API");

echo $mpesa->getDataFromCallback();```

**Comment by mossey** [comment]
Hey @KipchirchirIan Currently the sdk works well with Laravel. The env function works well with PHP. Just realized This.  I will make provisions so that It can work with all the other frameworks soon
